# This file was generated by GoReleaser. DO NOT EDIT.
cask "failsafe" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "d8374a4f79fb54b8333848b7fe01a33e54a0b3e9858f9e62b49f31a0ab732b7d"
      url "https://github.com/UndermountainCC/failsafe/releases/download/v#{version}/failsafe_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/UndermountainCC/failsafe/"
    end
    on_arm do
      sha256 "f87686b77dbef38f8ef2485b38c44fdeb8779f41df265475c68092b757bef4ea"
      url "https://github.com/UndermountainCC/failsafe/releases/download/v#{version}/failsafe_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/UndermountainCC/failsafe/"
    end
  end

  on_linux do
    on_intel do
      sha256 "7a0e1e60b917a1e651adf1304dce67448ce97364f4149fa9fd0062b41c05fcbe"
      url "https://github.com/UndermountainCC/failsafe/releases/download/v#{version}/failsafe_#{version}_linux_amd64.tar.gz",
        verified: "github.com/UndermountainCC/failsafe/"
    end
    on_arm do
      sha256 "cdd20c633590b0343068c7d308203a548cde1be376bebb880cc26eb9a33347f7"
      url "https://github.com/UndermountainCC/failsafe/releases/download/v#{version}/failsafe_#{version}_linux_arm64.tar.gz",
        verified: "github.com/UndermountainCC/failsafe/"
    end
  end

  name "failsafe"
  desc "The fail-safe for AI coding agents — stops the irreversible command before your agent runs it."
  homepage "https://failsafe.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "failsafe"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/failsafe"]
    end
  end

  # No zap stanza required

end
